### ISSUE TITLE
[Noetic] can't install both mrpt2 and mrpt_libposes; conflicting CKalmanFilterCapable.h

### ISSUE THREAD

**Issue by sloretz** [MRPT/mrpt_ros#1] opened 2024-09-03 19:12 UTC
This issue breaks the build of mrpt_localization, but I'm opening the issue here instead of https://github.com/mrpt-ros-pkg/mrpt_navigation because I suspect the root cause is here.

https://build.ros.org/view/Nbin_uF64/job/Nbin_uF64__mrpt_localization__ubuntu_focal_amd64__binary/121/consoleFull

It looks like the root cause of the `mrpt_localization` build failing is two packages trying to install the same header file:

```
05:52:40   5395 'Unpacking ros-noetic-mrpt2 (2.13.5-1focal.20240806.150347) ...'
05:52:40   5396 'dpkg: error processing archive /tmp/apt-dpkg-install-qN3u1I/1159-ros-noetic-mrpt2_2.13.5-1focal.20240806.150347_amd64.deb (--unpack):'
05:52:40   5397 ' trying to overwrite '/opt/ros/noetic/include/mrpt/bayes/include/mrpt/bayes/CKalmanFilterCapable.h', which is also in package ros-noetic-mrpt-libposes 2.13.7-2focal.20240825.172915'
```

**Comment by jlblancoc** [comment] 2024-09-04 12:36
Hmm... I see. That's because the ROS1 version of mrpt_navigation is basically EOL, and it depends on other packages that have been upgraded to use the new `mrpt_lib*` packages but it has not been upgraded yet.
I'll see if I can do it and make a new bloom-release of it...

**Comment by jlblancoc** [comment] 2024-09-04 14:53
@sloretz Should be fixed with https://github.com/ros/rosdistro/pull/42715

**Comment by jlblancoc** [comment] 2024-09-04 17:55
@sloretz I seems it got wrong here: 
https://build.ros.org/job/Nbin_uF64__mrpt_local_obstacles__ubuntu_focal_amd64__binary/89/console

I also saw exactly the same issue with another (cmake) Noetic package, so it must be something related to LD_LIBRARY_PATH (?). I'll try to fix it, but if the deadline approaches and you have to move on, feel free to remove the problematic packages for now... :-(

**Comment by jlblancoc** [comment] 2024-09-04 17:56
PS: It worked right in local ROS1 Noetic builds and in the farm's "-dev" builds, that's why I made the release. The issue has to do with debian dh_* tools...

**Comment by jlblancoc** [comment] 2024-09-05 07:03
@sloretz I fixed a coupled of issues, like patching the `debian/rules.em` for all failing mrpt_navigation and mrpt_slam packages and fixing typos in cmake scripts intended to work on both ros2 & ros1 (but was wrong for ros1), and made new releases: 
- https://github.com/ros/rosdistro/pull/42727
- https://github.com/ros/rosdistro/pull/42728
- https://github.com/ros/rosdistro/pull/42729

If you want to give them a try before the sync, or just remove the failing ones for this sync and hold them for the next one.

Thanks!

**Comment by sloretz** [comment] 2024-09-05 16:55
Thanks @jlblancoc ! I merged them to see if they fix the regressions.

**Comment by jlblancoc** [comment] 2024-09-05 20:13
@sloretz  Great, no regressions now! :-) 

There's only now one package failing (mp2p_icp for Noetic), but since there's no former release for it in ROS1, I guess it doesn't count as regression. Will try to get it green for the next cycle.

**Closed as completed by jlblancoc** 2024-09-05 20:13 UTC
